keys:
  - &diogo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICCTbCHJ0avif6MQ7izXlHHaubNsOhU2xf9lMvXKLyUQ

  - &iris age1x6rgrjkj0sx32apkg7fzsrgns8t524h3th0m8s30u08vl9lge9jqcvulxt

creation_rules:
  - path_regex: ^secrets/diogo\.yaml$
    key_groups:
      - age:
          - *diogo

  - path_regex: ^secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
          - *diogo
          - *iris
