keys:
  - &diogo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICCTbCHJ0avif6MQ7izXlHHaubNsOhU2xf9lMvXKLyUQ

  - &iris ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGlO5HxU1363XyNAvH4Cmi5lvoM5x0XQrWroelZ34Cx

creation_rules:
  - path_regex: ^secrets/diogo\.yaml$
    key_groups:
      - age:
          - *diogo

  - path_regex: ^secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
          - *diogo
          - *iris
